server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XU3IJ2x4kfUAKvBBI3hElSp+6MSdm7vJb9xKS+DeDsM3NHx815S8ahybOiX2OfluM4GBF9eDRIT8VZRMd+x4FyDXKkZMb24S9o91tAClsUCS/KYAF0gfb1ICPjUkK2nvtdgywOBR6dg=)
    username: ENC(aaq+Wjg1D1Z2cQGTwZeidA==)
    password: ENC(ggQPxMX7xD7eV2gA+GiPTm9Mm9+W6vso)
  mail:
    host: ENC(WaLpFXYKnKRNAsG1/p6McGLJrmMYyYN9)
    username: ENC(FRmnejafWbckb2gjtRaFBjY7S0CIkaK2L5v16Ggurl4=)
    password: ENC(d92dIj8dWEA9GQdto86LcTs4ZtmUqvTum4J4SccS8vQ=)
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: ENC(xGJHqtnNQ7QY0/Zmn7J3JVevS8FrsCLX)
    password: ENC(UBm3TeLHwCHy3FZXXk4ffZtulNrEz5zT)
yxt:
  jwt:
    secret: ENC(YKsuzaRh9wxvSPUYoxdZbNI7UWvy7WBgn8Ki2BF03iw=) # 登录校验的密钥
    pubKeyPath: D:\\data\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\data\\rsa\\rsa.pri # 私钥地址
    expire: 720 # 过期时间，单位分钟，默认为 900 = 60 * 12 即 12个小时
    userCookieName: YXT_USER_AUTH # 普通用户鉴权的 cookie 名称
    adminCookieName: YXT_ADMIN_AUTH # 管理员鉴权的 cookie 名称
    cookieMaxAge: 43200 # cookie 最大存活时间，单位秒，默认为 43200 = 60 * 60 * 12 即 12 个小时
  sms:
    accessKeyId: ENC(Ow/mUfbTm5er0W6d0Xu1qRsPSvJbT4DZJe265hyOvTGQAAVXfpxFMw==) # accessKeyId
    accessKeySecret: ENC(14dssZ3c/4duecBHqKSQ48eqrirA4vIC0uDAE+iEatP8IjTPD6I6dg==) # accessKeySecret
    signName: 有趣的pava # 签名名称
    verifyCodeTemplate: SMS_205139380 # 模板名称
logging:
  level:
    root: info
    com.yixuetang: debug
  file:
    name: log/yxt-dev.log
