server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XU3IJ2x4kfUAKvBBI3hElSp+6MSdm7vJb9xKS+DeDsM3NHx815S8ahybOiX2OfluM4GBF9eDRIT8VZRMd+x4FyDXKkZMb24S9o91tAClsUCS/KYAF0gfb1ICPjUkK2nvtdgywOBR6dg=)
    username: ENC(aaq+Wjg1D1Z2cQGTwZeidA==)
    password: ENC(ggQPxMX7xD7eV2gA+GiPTm9Mm9+W6vso)
jasypt:
  encryptor:
    password: ab88ae481830055fe126c7289x6d78c8
yxt:
  jwt:
    secret: 11YXT_USER_AUTH44@ # 登录校验的密钥
    pubKeyPath: E:\\projects\\yxt-edu\\yxt-edu-service\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\\projects\\yxt-edu\\yxt-edu-service\\rsa\\rsa.pri # 私钥地址
    expire: 900 # 过期时间，单位分钟，默认为 900 = 60 * 15 即 15个小时
    cookieName: YXT_USER_AUTH # cookie名称
    cookieMaxAge: 54000 # cookie 最大存活时间，单位秒，默认为 54000 = 60 * 60 * 15 即 15 个小时
logging:
  level:
    root: info
    com.yixuetang: debug
  file:
    name: log/yxt-dev.log
